export { default as Spinner } from "./UI/Spinner"
export { default as ToggleSwitch } from "./UI/ToggleSwitch"
export { default as SectionTitle } from "./UI/SectionTitle"
export { default as FavoriteBtn } from "./UI/FavoriteBtn"

export { default as Header } from "./Header"
export { default as Search } from "./Search"
export { default as Favorites } from "./Favorites"
export { default as CurrentWeather } from "./CurrentWeather"
export { default as Forecast } from "./Forecast"
export { default as Footer } from "./Footer"
